server:
    port: 8888

database:
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    dbname: goadmin_utest
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600  # 1 hour in seconds
    show_sql: true

jwt:
    secret: your_jwt_secret_key
    access_token_exp: 8h
    refresh_token_exp: 7d

logger:
    log_file: "./logs/app.log"
    level: "info"
    max_size: 100  # 100 MB
    max_backups: 3
    max_age: 28  # 28 days
    compress: true
    console: true

opentelemetry:
    enable: true         # 启用OpenTelemetry
    service: go-admin   # 服务名称
    endpoint: 127.0.0.1:4318 # Jaeger地址
    protocol: http # Jaeger协议
    sampling: 1.0  # 开发环境建议全采样
    timeout: 5           # 超时时间5秒
