server:
    port: 8888

database:
    host: 127.0.0.1
    port: 3306
    user: go_user
    password: go_user123
    dbname: go_admin
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600  # 1 hour in seconds
    show_sql: false

jwt:
    secret: your_jwt_secret_key
    access_token_exp: 8h
    refresh_token_exp: 7d

logger:
    log_file: "./logs/app.log"
    level: "info"
    max_size: 100  # 100 MB
    max_backups: 3
    max_age: 28  # 28 days
    compress: true
    console: true

opentelemetry:
    enable: true         # 启用OpenTelemetry
    service: go-admin   # 服务名称
    endpoint: 127.0.0.1:43170 # Jaeger地址
    protocol: grpc # Jaeger协议
    sampling: 1.0  # 开发环境建议全采样
    timeout: 5           # 超时时间5秒

tasks:
  - name: health_task
    cron_expr: "*/1 * * * *"
    disabled: true
