global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'go_app'
    static_configs:
      - targets: ['app1:8888', 'app2:8888']
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.+):\d+'
        replacement: '$1'

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']  # Jaeger 默认在 14269 端口暴露 Prometheus 指标
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']  # 假设 Collector 在 8888 端口暴露指标
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:9090']
    metrics_path: '/metrics'
    scheme: 'http'