package routegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

// Render 生成 router 包内的 routes_gen.go 源码。
func Render(routes []Route) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by routegen; DO NOT EDIT.\n\n")
	b.WriteString("package router\n\n")
	b.WriteString("func init() {\n")
	if len(routes) == 0 {
		b.WriteString("\t// 未扫描到任何 @route\n")
	}
	for _, r := range routes {
		fmt.Fprintf(&b, "\tregisterCompiledRoute(%q, %q, %q, %s, %q)\n",
			r.PkgPath, r.TypeName, r.MethodName, strings.ToUpper(r.HTTPMethod), r.Path)
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("routegen: format generated source: %w\n%s", err, b.String())
	}
	return formatted, nil
}
