package routegen

import (
	"path/filepath"
	"runtime"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func moduleRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	require.True(t, ok)
	// .../internal/platform/routegen/scan_test.go -> 模块根
	root := filepath.Clean(filepath.Join(filepath.Dir(file), "..", "..", ".."))
	return root
}

func TestExtractRouteTag(t *testing.T) {
	tests := []struct {
		name    string
		comment string
		ok      bool
		method  string
		path    string
	}{
		{name: "POST /login", comment: "// @route POST /login", ok: true, method: "POST", path: "/login"},
		{name: "GET /refresh", comment: "// @route GET /refresh", ok: true, method: "GET", path: "/refresh"},
		{name: "大小写不敏感", comment: "// @route Post /user/assign/roles", ok: true, method: "POST", path: "/user/assign/roles"},
		{name: "普通注释", comment: "这是普通注释", ok: false},
		{name: "行首@route", comment: "@route POST /logout", ok: true, method: "POST", path: "/logout"},
		{name: "格式不正确", comment: "// @routePOST/logout", ok: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			method, path, ok := ExtractRouteTag(tt.comment)
			assert.Equal(t, tt.ok, ok)
			if tt.ok {
				assert.Equal(t, tt.method, method)
				assert.Equal(t, tt.path, path)
			}
		})
	}
}

func TestScanModule_ContainsAssignRoles(t *testing.T) {
	routes, err := ScanModule(moduleRoot(t))
	require.NoError(t, err)
	require.NotEmpty(t, routes)

	wantKey := "github.com/ayxworxfr/go_admin/internal/modules/iam/handler.UserRoleHandler.UserAssignRoles"
	var found *Route
	for i := range routes {
		if routes[i].Key() == wantKey {
			found = &routes[i]
			break
		}
	}
	require.NotNil(t, found, "应扫描到 UserAssignRoles")
	assert.Equal(t, "POST", found.HTTPMethod)
	assert.Equal(t, "/user/assign/roles", found.Path)
}

func TestRender_Stable(t *testing.T) {
	src, err := Render([]Route{{
		PkgPath:    "example.com/app/handler",
		TypeName:   "H",
		MethodName: "Login",
		HTTPMethod: "POST",
		Path:       "/login",
	}})
	require.NoError(t, err)
	assert.Contains(t, string(src), "Code generated by routegen")
	assert.Contains(t, string(src), `registerCompiledRoute("example.com/app/handler", "H", "Login", POST, "/login")`)
}
